import torch
import numpy as np
from einops import rearrange
import cv2
import os
import zipfile
import pandas as pd
import io
import tempfile
from torch.utils.data import Dataset
import sys

# Add current directory to path to import config
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from config import Config

class NvidiaDatasetParser:
    def __init__(self, target_size=Config.IMAGE_SIZE):
        self.target_size = target_size
        self.camera_names = [
            "camera_cross_left_120fov",
            "camera_front_wide_120fov",
            "camera_cross_right_120fov",
            "camera_rear_left_70fov",
            "camera_rear_tele_30fov",
            "camera_rear_right_70fov",
            "camera_front_tele_30fov",
        ]

    def preprocess_image(self, image):
        # Resize to target size
        image = cv2.resize(image, self.target_size)
        # Convert to tensor and normalize
        image = torch.from_numpy(image).float() / 255.0
        # Rearrange to (C, H, W)
        image = rearrange(image, "c h w" if image.shape[0] == 3 else "h w c -> c h w")
        return image

    def format_input(self, cameras_data, egomotion_data, map_tile=None):
        """
        cameras_data: dict of camera_name -> image (H, W, 3)
        egomotion_data: numpy array or list of 64 steps * 4 features (256)
        map_tile: optional image (H, W, 3)
        """
        # 1. Process 7 cameras
        visual_tiles_list = []
        for cam_name in self.camera_names:
            if cam_name in cameras_data:
                img = self.preprocess_image(cameras_data[cam_name])
            else:
                # Placeholder for missing camera
                img = torch.zeros(3, *self.target_size)
            visual_tiles_list.append(img)
        
        # 2. Add map tile
        if map_tile is not None:
            map_img = self.preprocess_image(map_tile)
        else:
            # Placeholder for map tile
            map_img = torch.zeros(3, *self.target_size)
        visual_tiles_list.append(map_img)
        
        visual_tiles = torch.stack(visual_tiles_list) # (8, 3, 224, 224)
        
        # 3. Process egomotion history
        egomotion_history = torch.tensor(egomotion_data).float()
        if egomotion_history.numel() != 256:
            # Pad or truncate to 256
            if egomotion_history.numel() < 256:
                egomotion_history = torch.cat([egomotion_history, torch.zeros(256 - egomotion_history.numel())])
            else:
                egomotion_history = egomotion_history[:256]
        
        # 4. Visual history (placeholder as it's generated by the model)
        visual_history = torch.zeros(896)
        
        return visual_tiles, egomotion_history, visual_history

class PhysicalAIDataset(Dataset):
    def __init__(self, snapshot_path, clip_ids, cameras=["camera_front_wide_120fov"]):
        self.snapshot_path = snapshot_path
        self.clip_ids = clip_ids
        self.cameras = cameras
        self.parser = NvidiaDatasetParser()
        
        # Load clip index to know chunks
        idx_path = os.path.join(snapshot_path, "clip_index.parquet")
        self.df_index = pd.read_parquet(idx_path)
        
    def __len__(self):
        return len(self.clip_ids)
    
    def __getitem__(self, idx):
        clip_id = self.clip_ids[idx]
        chunk_num = self.df_index.loc[clip_id, "chunk"]
        
        # 1. Load Egomotion (Labels/Trajectory)
        egomotion_zip = os.path.join(self.snapshot_path, f"labels/egomotion/egomotion.chunk_{chunk_num:04d}.zip")
        target_traj = np.zeros(128)
        egomotion_history = np.zeros(256)
        
        if os.path.exists(egomotion_zip):
            try:
                with zipfile.ZipFile(egomotion_zip, 'r') as z:
                    parquet_name = f"{clip_id}.egomotion.parquet"
                    if parquet_name in z.namelist():
                        with z.open(parquet_name) as f:
                            df_ego = pd.read_parquet(io.BytesIO(f.read()))
                            ego_subset = df_ego.head(64)
                            accel = ego_subset['ax'].values
                            curv = ego_subset['curvature'].values
                            target_traj = np.stack([accel, curv], axis=1).flatten()
                            
                            egomotion_history = np.stack([
                                ego_subset['vx'].values, 
                                ego_subset['vy'].values, 
                                ego_subset['ax'].values, 
                                ego_subset['curvature'].values
                            ], axis=1).flatten()
            except Exception as e:
                print(f"Error reading egomotion for {clip_id}: {e}")

        # 2. Load Cameras
        cameras_data = {}
        for cam in self.cameras:
            cam_zip = os.path.join(self.snapshot_path, f"camera/{cam}/{cam}.chunk_{chunk_num:04d}.zip")
            if os.path.exists(cam_zip):
                try:
                    with zipfile.ZipFile(cam_zip, 'r') as z:
                        mp4_name = f"{clip_id}.{cam}.mp4"
                        if mp4_name in z.namelist():
                            with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp:
                                tmp.write(z.read(mp4_name))
                                tmp_path = tmp.name
                            
                            cap = cv2.VideoCapture(tmp_path)
                            ret, frame = cap.read()
                            if ret:
                                cameras_data[cam] = frame
                            cap.release()
                            os.unlink(tmp_path)
                except Exception as e:
                    print(f"Error reading camera {cam} for {clip_id}: {e}")

        vt, eh, vh = self.parser.format_input(cameras_data, egomotion_history)
        
        return {
            "visual_tiles": vt,
            "egomotion_history": eh,
            "visual_history": vh,
            "target_trajectory": torch.tensor(target_traj).float(),
            "clip_id": clip_id
        }

def load_dataset(country=Config.TARGET_COUNTRY):
    """
    Actually loads real data if available for the specified country.
    """
    snapshot_path = Config.SNAPSHOT_PATH
    if not os.path.exists(snapshot_path):
        print(f"Snapshot not found at {snapshot_path}")
        return None
    
    country_file = f"{country.lower()}_clips.txt"
    if not os.path.exists(country_file):
        # Fallback to general list if specific country file missing
        if country.lower() == "spain" and os.path.exists("spain_clips.txt"):
            country_file = "spain_clips.txt"
        else:
            print(f"Clip list for {country} not found ({country_file}). Run dataset_manager.py first.")
            return None
    
    with open(country_file, "r") as f:
        clips = [line.strip() for line in f.readlines()]
    
    idx_path = os.path.join(snapshot_path, "clip_index.parquet")
    df_index = pd.read_parquet(idx_path)
    
    available_clips = []
    for cid in clips:
        if cid in df_index.index:
            chunk_num = df_index.loc[cid, "chunk"]
            egomotion_zip = os.path.join(snapshot_path, f"labels/egomotion/egomotion.chunk_{chunk_num:04d}.zip")
            if os.path.exists(egomotion_zip):
                available_clips.append(cid)
    
    if not available_clips:
        print(f"No downloaded chunks found for {country} clips in {snapshot_path}")
        return None

    dataset = PhysicalAIDataset(snapshot_path, available_clips)
    return dataset

# For backward compatibility
def load_spain_subset():
    return load_dataset("Spain")

if __name__ == "__main__":
    Config.print_config()
    ds = load_dataset()
    if ds and len(ds) > 0:
        sample = ds[0]
        print(f"Loaded clip: {sample['clip_id']}")
        print(f"Visual Tiles Shape: {sample['visual_tiles'].shape}")
        print(f"Target Trajectory Shape: {sample['target_trajectory'].shape}")
    else:
        print("No clips loaded.")
